# fly.toml app configuration file generated for voice-memo-bot on 2023-06-01T12:49:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "voice-memo-bot"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "dfw"
  SERVICE_PUBLIC_URL = "https://voice-memo-bot.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
