# fly.toml app configuration file generated for voice-memo-bot on 2023-04-19T10:30:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "voice-memo-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"
processes = []

[build]

[env]
  SERVICE_PUBLIC_URL = "https://voice-memo-bot.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  autostart = true
  autostop = false
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
